
{'date': 'Mon Jun 28 2021 17:58:04.384 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 5
  class Move
             ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 28 2021 18:04:29.908 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 9
  self.movente = Elemento("https://i.imgur.com/slnDrGI.png", cena=self.cena,
                                                                                                                                          ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 28 2021 18:37:00.671 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 12
  Texto(self.parede "veja a proteina chegar na parede", foi=self.mover
                     ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 28 2021 18:37:26.555 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 17
    Move()
  module <module> line 9
    self.cena.vai()
AttributeError: 'Move' object has no attribute 'cena'
'''},
{'date': 'Mon Jun 28 2021 22:23:50.13 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 13
  self.multi = Texto(self.parede, "processos corretos?"
                                                                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 28 2021 22:39:03.371 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 33
    Move()
  module <module> line 13
    self.pergunta()
  module <module> line 16
    if self.acabou:
AttributeError: 'Move' object has no attribute 'acabou'
'''},
{'date': 'Mon Jun 28 2021 22:39:09.609 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 33
    Move()
  module <module> line 13
    self.pergunta()
  module <module> line 16
    if self.acabou:
AttributeError: 'Move' object has no attribute 'acabou'
'''},
{'date': 'Wed Jun 30 2021 19:35:02.997 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 19
  self.celular = Elemento(img=CELULAR, x=800, y=500, w=100, h=100 cena=self.parede)
                                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Jun 30 2021 19:35:26.322 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 71
    Move()
  module <module> line 14
    MOCHILA.quando_pega(self.pegou_atp)
AttributeError: 'Mochila' object has no attribute 'quando_pega'
'''},
{'date': 'Wed Jun 30 2021 20:02:44.968 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 79
    Move()
  module <module> line 16
    MOCHILA.esvazia_mochila()
AttributeError: 'Mochila' object has no attribute 'esvazia_mochila'
'''},
{'date': 'Wed Jun 30 2021 20:33:17.29 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 33
  self.organela = Elemento(img=RIBOSSOMA, x=300, y=600, w=60, h=60, y=100, cena=self.parede)
                                                                     ^
SyntaxError: keyword argument repeated
'''},
{'date': 'Wed Jun 30 2021 20:46:22.885 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    Move()
  module <module> line 31
    self.movente.elt.ontransitionend = self.persegue_maria
AttributeError: 'Move' object has no attribute 'persegue_maria'
'''},
{'date': 'Wed Jun 30 2021 20:46:39.878 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    Move()
  module <module> line 31
    self.movente.elt.ontransitionend = self.persegue_maria
AttributeError: 'Move' object has no attribute 'persegue_maria'
'''},
{'date': 'Fri Jul 02 2021 13:25:30.141 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 57
  Texto(self.parede, txt, A="Complexo de Golgi", B="Ribossomo", C"Vacúolo").vai()
                                                                  ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 02 2021 13:25:51.971 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 64
  Texto(self.parede, txt, foi=self.vai_embora).vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Jul 02 2021 17:53:55.336 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 116
  class Fase7()
                ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 02 2021 17:54:04.485 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 148
  self.ribossomo=Personagem(img=ribossomo,x=0, afala="No caminho eu te explico...",responde=)
                                                                                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 02 2021 17:56:31.628 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 157
    Fase7()     
  module <module> line 136
    self.glicose = Personagem(GLICOSE, tit="glicose", x=0, y=100,
TypeError: __init__() got an unexpected keyword argument 'tit'
'''},
{'date': 'Fri Jul 02 2021 18:00:51.142 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 159
    Fase7()     
  module <module> line 136
    self.glicose = Personagem(GLICOSE, x=0, y=100,
TypeError: __init__() got an unexpected keyword argument 'cena'
'''},
{'date': 'Fri Jul 02 2021 18:03:34.946 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 161
    Fase7()     
  module <module> line 144
    self.maria=Personagem(img=MARIA, x=0, y=400, w=100, h=200, afala=afala, responde=self.ribossomo)
AttributeError: 'Fase7' object has no attribute 'ribossomo'
'''},
{'date': 'Fri Jul 02 2021 18:17:50.894 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 162
    Fase7()     
  module <module> line 141
    self.ribossoma = Personagem(RIBOSSOMA, x=200, y=200, w=80, h=80, afala=afala,
AttributeError: 'Fase7' object has no attribute 'glicose_fake'
'''},
{'date': 'Fri Jul 02 2021 18:49:58.470 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 175
  self.maria.style= {"transition": "left 4s"})
                                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Thu Feb 10 2022 15:32:13.416 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 204
  LABORATORIO="https://i.imgur.com/g3wt0Vb.jpg"
  ^
IndentationError: expected an indented block
'''},
{'date': 'Thu Feb 10 2022 15:33:03.736 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 232
  if __name__ == "__main__": 
  ^
IndentationError: unexpected indent
'''},